import { StyleSheet, Platform } from 'react-native';
import { C, rs, fs } from '../design-tokens';

export const s = StyleSheet.create({
  flex: { flex: 1, backgroundColor: C.bg },
  safe: { flex: 1, backgroundColor: C.bg, paddingTop: Platform.OS === 'android' ? rs(40) : 0 },
  loginContainer: { flex: 1, justifyContent: 'center', padding: rs(24), backgroundColor: C.bg },
  loginTitle: { fontSize: fs(26), fontWeight: 'bold', color: C.textPrimary, textAlign: 'center', marginBottom: rs(28) },
  msgBanner: { backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: rs(1), borderColor: C.accent, borderRadius: rs(8), padding: rs(12), marginBottom: rs(16) },
  msgText: { color: '#e0f2fe', textAlign: 'center' },
  input: { backgroundColor: 'rgba(15,23,42,0.6)', borderWidth: rs(1), borderColor: C.border, borderRadius: rs(8), padding: rs(14), color: C.textPrimary, fontSize: fs(16), marginBottom: rs(12) },
  btn: { backgroundColor: C.accent, padding: rs(16), borderRadius: rs(8), alignItems: 'center', marginBottom: rs(8) },
  btnText: { color: C.bg, fontWeight: 'bold', fontSize: fs(16) },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: rs(16), paddingTop: rs(16), paddingBottom: rs(8) },
  headerTitle: { fontSize: fs(22), fontWeight: 'bold', color: C.textPrimary },
  signOutBtn: { backgroundColor: 'rgba(255,255,255,0.08)', paddingVertical: rs(8), paddingHorizontal: rs(12), borderRadius: rs(8) },
  errorBanner: { backgroundColor: 'rgba(239,68,68,0.15)', borderWidth: rs(1), borderColor: C.error, borderRadius: rs(8), padding: rs(12), marginHorizontal: rs(16), marginBottom: rs(8) },
  sectionTitle: { fontSize: fs(17), fontWeight: '600', color: '#e2e8f0', marginBottom: rs(12) },
  macroGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: rs(10) },
  macroCard: { flex: 1, minWidth: '44%', backgroundColor: C.surface, padding: rs(16), borderRadius: rs(14), borderTopWidth: rs(3), borderTopColor: C.accent, alignItems: 'center' },
  macroLabel: { color: C.textSecondary, fontSize: fs(11), textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: rs(6) },
  macroValue: { color: C.textPrimary, fontSize: fs(22), fontWeight: 'bold' },
  macroUnit: { color: C.textMuted, fontSize: fs(11), marginTop: rs(2) },
  logForm: { flexDirection: 'row', gap: rs(8), alignItems: 'center' },
  logBtn: { backgroundColor: C.accent, paddingHorizontal: rs(18), paddingVertical: rs(14), borderRadius: rs(8), justifyContent: 'center', alignItems: 'center' },
  logItem: { backgroundColor: 'rgba(30,41,59,0.5)', padding: rs(14), borderRadius: rs(12), marginBottom: rs(10), flexDirection: 'row', alignItems: 'center' },
  logName: { color: C.textPrimary, fontSize: fs(15), fontWeight: '500' },
  chip: { color: C.textSecondary, fontSize: fs(12), backgroundColor: 'rgba(15,23,42,0.5)', paddingHorizontal: rs(8), paddingVertical: rs(3), borderRadius: rs(4) },
  tabBar: { flexDirection: 'row', backgroundColor: 'rgba(15,23,42,0.95)', borderTopWidth: rs(1), borderTopColor: C.border, paddingBottom: Platform.OS === 'ios' ? rs(24) : rs(12), paddingTop: rs(12) },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabIcon: { fontSize: fs(24), marginBottom: rs(4) },
  tabLabel: { fontSize: fs(12), color: C.textSecondary, fontWeight: '500' },
  activeDot: { width: rs(4), height: rs(4), borderRadius: rs(2), backgroundColor: C.accent, marginTop: rs(4) },
  optionBtn: { backgroundColor: C.surface, borderWidth: rs(1), borderColor: 'transparent', borderRadius: rs(8), alignItems: 'center' },
  optionBtnSelected: { borderColor: C.accent, backgroundColor: 'rgba(56,189,248,0.15)' },
  optionText: { color: C.textSecondary, fontSize: fs(14), fontWeight: '500' },
  optionTextSelected: { color: C.accent, fontWeight: 'bold' },
  avatarPlaceholder: { width: rs(80), height: rs(80), borderRadius: rs(40), backgroundColor: 'rgba(56,189,248,0.2)', justifyContent: 'center', alignItems: 'center', marginBottom: rs(12) },
  avatarText: { fontSize: fs(32) },
  cardContainer: { backgroundColor: C.surface, borderRadius: rs(14), padding: rs(16), marginBottom: rs(16) },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: rs(12), borderBottomWidth: rs(1), borderBottomColor: 'rgba(255,255,255,0.05)' },
  detailLabel: { color: C.textSecondary, fontSize: fs(15) },
  detailValue: { color: C.textPrimary, fontSize: fs(15), fontWeight: '500', textTransform: 'capitalize' },
  confirmationCard: { backgroundColor: C.surface, padding: rs(16), borderRadius: rs(14), borderWidth: rs(1), borderColor: C.border },
  editRow: { backgroundColor: 'rgba(15,23,42,0.4)', borderRadius: rs(8), paddingHorizontal: rs(12), paddingVertical: rs(8), marginBottom: rs(8), flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  editLabel: { color: C.textSecondary, fontSize: fs(12), textTransform: 'uppercase', fontWeight: 'bold' },
  editInput: { color: C.textPrimary, fontSize: fs(16), fontWeight: '600', textAlign: 'right', padding: rs(0), margin: rs(0), minWidth: rs(60) },
  mealTypePill: { paddingHorizontal: rs(12), paddingVertical: rs(6), borderRadius: rs(16), backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: rs(1), borderColor: 'transparent' },
  mealTypePillActive: { backgroundColor: 'rgba(56,189,248,0.1)', borderColor: C.accent },
  mealTypeText: { color: C.textSecondary, fontSize: fs(13), fontWeight: '500' },
  mealTypeTextActive: { color: C.accent, fontWeight: 'bold' }
});
