import { StyleSheet } from 'react-native';
import { C, rs, fs } from '../design-tokens';

export const fitnessStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  subTabContainer: {
    flexDirection: 'row',
    paddingHorizontal: rs(16),
    paddingVertical: rs(12),
    gap: rs(8),
    backgroundColor: 'rgba(15,23,42,0.4)',
    borderBottomWidth: rs(1),
    borderBottomColor: C.border,
  },
  subTabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(30,41,59,0.3)',
    borderWidth: rs(1),
    borderColor: C.border,
    borderRadius: rs(10),
    paddingVertical: rs(10),
    gap: rs(6),
  },
  subTabButtonActive: {
    backgroundColor: C.accent,
    borderColor: C.accent,
  },
  subTabButtonText: {
    color: C.textSecondary,
    fontWeight: '600',
    fontSize: fs(12),
  },
  subTabButtonTextActive: {
    color: C.bg,
    fontWeight: 'bold',
  },
  scrollContent: {
    padding: rs(16),
    paddingBottom: rs(40),
  },
  sectionTitle: {
    fontSize: fs(17),
    fontWeight: '600',
    color: '#e2e8f0',
    marginBottom: rs(12),
    marginTop: rs(8),
  },
  formCard: {
    backgroundColor: C.surface,
    padding: rs(16),
    borderRadius: rs(14),
    marginBottom: rs(20),
    borderWidth: rs(1),
    borderColor: C.border,
  },
  formRow: {
    flexDirection: 'row',
    gap: rs(12),
  },
  inputGroup: {
    marginBottom: rs(12),
  },
  inputLabel: {
    color: C.textSecondary,
    fontSize: fs(12),
    fontWeight: '500',
    marginBottom: rs(6),
  },
  formInput: {
    backgroundColor: 'rgba(15,23,42,0.5)',
    borderWidth: rs(1),
    borderColor: C.border,
    borderRadius: rs(8),
    paddingHorizontal: rs(12),
    paddingVertical: rs(10),
    color: C.textPrimary,
    fontSize: fs(15),
  },
  exerciseCard: {
    backgroundColor: C.surface,
    borderRadius: rs(14),
    padding: rs(12),
    marginBottom: rs(12),
    borderWidth: rs(1),
    borderColor: C.border,
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(12),
    marginBottom: rs(12),
  },
  exerciseThumb: {
    width: rs(48),
    height: rs(48),
    borderRadius: rs(8),
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  exerciseTitle: {
    color: C.textPrimary,
    fontSize: fs(15),
    fontWeight: '600',
    textTransform: 'capitalize',
    marginBottom: rs(4),
  },
  muscleBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(56,189,248,0.1)',
    paddingHorizontal: rs(6),
    paddingVertical: rs(2),
    borderRadius: rs(4),
    borderWidth: rs(1),
    borderColor: 'rgba(56,189,248,0.2)',
  },
  muscleText: {
    color: C.accent,
    fontSize: fs(10),
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  removeBtn: {
    padding: rs(6),
  },
  inputsRow: {
    flexDirection: 'row',
    gap: rs(8),
  },
  exerciseInputCol: {
    flex: 1,
    alignItems: 'center',
  },
  exerciseInputLabel: {
    color: C.textMuted,
    fontSize: fs(10),
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: rs(4),
  },
  exerciseInput: {
    backgroundColor: 'rgba(15,23,42,0.4)',
    borderWidth: rs(1),
    borderColor: C.border,
    borderRadius: rs(6),
    width: '100%',
    paddingVertical: rs(6),
    color: C.textPrimary,
    fontSize: fs(14),
    fontWeight: '600',
    textAlign: 'center',
  },
  searchBoxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.5)',
    borderWidth: rs(1),
    borderColor: C.border,
    borderRadius: rs(10),
    paddingHorizontal: rs(12),
    marginBottom: rs(16),
  },
  searchIcon: {
    marginRight: rs(8),
  },
  searchInput: {
    flex: 1,
    paddingVertical: rs(10),
    color: C.textPrimary,
    fontSize: fs(15),
  },
  clearSearchBtn: {
    padding: rs(6),
  },
  searchResultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.surface,
    padding: rs(10),
    borderRadius: rs(10),
    marginBottom: rs(8),
    borderWidth: rs(1),
    borderColor: C.border,
  },
  searchResultTextContainer: {
    flex: 1,
    marginLeft: rs(12),
    justifyContent: 'center',
  },
  searchResultTitle: {
    color: C.textPrimary,
    fontSize: fs(14),
    fontWeight: '600',
    textTransform: 'capitalize',
    marginBottom: rs(4),
  },
  searchResultMeta: {
    flexDirection: 'row',
    gap: rs(6),
  },
  addResultBtn: {
    backgroundColor: C.accent,
    width: rs(32),
    height: rs(32),
    borderRadius: rs(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitBtn: {
    backgroundColor: C.accent,
    paddingVertical: rs(14),
    borderRadius: rs(10),
    alignItems: 'center',
    marginTop: rs(16),
    marginBottom: rs(24),
  },
  submitBtnDisabled: {
    backgroundColor: C.textMuted,
    opacity: 0.6,
  },
  submitBtnText: {
    color: C.bg,
    fontSize: fs(16),
    fontWeight: 'bold',
  },
  historyCard: {
    backgroundColor: C.surface,
    borderRadius: rs(14),
    padding: rs(16),
    marginBottom: rs(12),
    borderWidth: rs(1),
    borderColor: C.border,
    borderLeftWidth: rs(4),
    borderLeftColor: C.accent,
  },
  historyCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: rs(8),
  },
  historyWorkoutName: {
    color: C.textPrimary,
    fontSize: fs(16),
    fontWeight: '600',
    flex: 1,
  },
  historyCaloriesBadge: {
    backgroundColor: 'rgba(249,115,22,0.15)',
    borderWidth: rs(1),
    borderColor: 'rgba(249,115,22,0.3)',
    borderRadius: rs(6),
    paddingHorizontal: rs(8),
    paddingVertical: rs(4),
    marginLeft: rs(8),
  },
  historyCaloriesText: {
    color: C.cal,
    fontSize: fs(12),
    fontWeight: 'bold',
  },
  historyMetaRow: {
    flexDirection: 'row',
    gap: rs(12),
    marginBottom: rs(12),
  },
  historyMetaItem: {
    color: C.textSecondary,
    fontSize: fs(12),
  },
  historyNotes: {
    color: C.textMuted,
    fontSize: fs(12),
    fontStyle: 'italic',
    backgroundColor: 'rgba(15,23,42,0.3)',
    padding: rs(8),
    borderRadius: rs(6),
    marginBottom: rs(12),
  },
  historySetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(8),
    marginTop: rs(4),
  },
  historySetName: {
    color: C.textSecondary,
    fontSize: fs(13),
    fontWeight: '500',
    textTransform: 'capitalize',
    flex: 1,
  },
  historySetDetails: {
    color: C.textMuted,
    fontSize: fs(12),
  },
  emptyText: {
    color: C.textMuted,
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: rs(24),
    fontSize: fs(14),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: rs(20),
  },
  modalContent: {
    backgroundColor: C.surface,
    borderRadius: rs(20),
    borderWidth: rs(1),
    borderColor: C.border,
    width: '100%',
    maxHeight: '90%',
    overflow: 'hidden',
  },
  modalScroll: {
    padding: rs(20),
  },
  modalCloseBtn: {
    alignSelf: 'flex-end',
    padding: rs(8),
  },
  modalGif: {
    width: rs(220),
    height: rs(220),
    borderRadius: rs(16),
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    marginBottom: rs(20),
  },
  modalTitle: {
    color: C.textPrimary,
    fontSize: fs(22),
    fontWeight: 'bold',
    textAlign: 'center',
    textTransform: 'capitalize',
    marginBottom: rs(12),
  },
  modalBadgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: rs(8),
    marginBottom: rs(20),
  },
  modalBadge: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: rs(10),
    paddingVertical: rs(4),
    borderRadius: rs(6),
    borderWidth: rs(1),
    borderColor: 'rgba(255,255,255,0.1)',
  },
  modalBadgeText: {
    color: C.textSecondary,
    fontSize: fs(11),
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  modalInstructionSection: {
    marginBottom: rs(24),
  },
  modalSectionTitle: {
    color: C.textPrimary,
    fontSize: fs(16),
    fontWeight: '600',
    marginBottom: rs(12),
  },
  instructionStep: {
    flexDirection: 'row',
    gap: rs(12),
    marginBottom: rs(10),
  },
  stepNumberContainer: {
    backgroundColor: C.accent,
    width: rs(20),
    height: rs(20),
    borderRadius: rs(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: rs(2),
  },
  stepNumber: {
    color: C.bg,
    fontSize: fs(11),
    fontWeight: 'bold',
  },
  stepText: {
    color: C.textSecondary,
    fontSize: fs(14),
    lineHeight: rs(20),
    flex: 1,
  },
  modalAddBtn: {
    backgroundColor: C.accent,
    paddingVertical: rs(14),
    borderRadius: rs(10),
    alignItems: 'center',
    marginBottom: rs(12),
  },
  modalAddBtnText: {
    color: C.bg,
    fontSize: fs(16),
    fontWeight: 'bold',
  },
  routineCard: {
    backgroundColor: C.surface,
    borderRadius: rs(14),
    padding: rs(16),
    marginBottom: rs(16),
    borderWidth: rs(1),
    borderColor: C.border,
  },
  routineHeader: {
    marginBottom: rs(12),
  },
  routineTitle: {
    color: C.textPrimary,
    fontSize: fs(17),
    fontWeight: 'bold',
    marginBottom: rs(4),
  },
  routineDesc: {
    color: C.textSecondary,
    fontSize: fs(13),
  },
  routineExerciseList: {
    marginBottom: rs(16),
    backgroundColor: 'rgba(15,23,42,0.3)',
    padding: rs(12),
    borderRadius: rs(10),
  },
  routineExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(8),
    marginVertical: rs(4),
  },
  routineExerciseText: {
    color: C.textPrimary,
    fontSize: fs(14),
    textTransform: 'capitalize',
    flex: 1,
  },
  routineExerciseDetails: {
    color: C.textMuted,
    fontSize: fs(12),
  },
  routineStartBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.accent,
    paddingVertical: rs(12),
    borderRadius: rs(10),
    gap: rs(8),
  },
  routineStartBtnText: {
    color: C.bg,
    fontSize: fs(14),
    fontWeight: 'bold',
  },
});


