"""alter foodlog created_at default

Revision ID: 00dbfb7c34e3
Revises: ce88a35c104e
Create Date: 2026-06-16 18:29:18.563361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00dbfb7c34e3'
down_revision: Union[str, Sequence[str], None] = 'ce88a35c104e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
