"""Add RoutineDay and update RoutineExercise

Revision ID: 2dd722911712
Revises: 906228342c1f
Create Date: 2026-06-18 18:05:05.711701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2dd722911712'
down_revision: Union[str, Sequence[str], None] = '906228342c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routineexercise', sa.Column('day_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_routineexercise_routine_id'), table_name='routineexercise')
    op.create_index(op.f('ix_routineexercise_day_id'), 'routineexercise', ['day_id'], unique=False)
    op.drop_constraint(op.f('routineexercise_routine_id_fkey'), 'routineexercise', type_='foreignkey')
    op.create_foreign_key(None, 'routineexercise', 'routineday', ['day_id'], ['id'])
    op.drop_column('routineexercise', 'routine_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routineexercise', sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'routineexercise', type_='foreignkey')
    op.create_foreign_key(op.f('routineexercise_routine_id_fkey'), 'routineexercise', 'routine', ['routine_id'], ['id'])
    op.drop_index(op.f('ix_routineexercise_day_id'), table_name='routineexercise')
    op.create_index(op.f('ix_routineexercise_routine_id'), 'routineexercise', ['routine_id'], unique=False)
    op.drop_column('routineexercise', 'day_id')
    # ### end Alembic commands ###
