"""add_meal_type

Revision ID: 3bfb13ec4649
Revises: 501ea3b563b6
Create Date: 2026-06-17 23:22:25.742128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bfb13ec4649'
down_revision: Union[str, Sequence[str], None] = '501ea3b563b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodlog', sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodlog', 'meal_type')
    # ### end Alembic commands ###
