"""add_workout_tables

Revision ID: 4402fd76bc9f
Revises: 611851e8cb64
Create Date: 2026-06-18 15:29:29.193092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4402fd76bc9f'
down_revision: Union[str, Sequence[str], None] = '611851e8cb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gif_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_parts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('equipments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_muscles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_muscles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_exercise_id'), 'exercise', ['exercise_id'], unique=True)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_table('workoutsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workoutsession_user_id'), 'workoutsession', ['user_id'], unique=False)
    op.create_table('workoutset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workoutsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workoutset_session_id'), 'workoutset', ['session_id'], unique=False)
    op.drop_column('foodlog', 'reasoning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodlog', sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workoutset_session_id'), table_name='workoutset')
    op.drop_table('workoutset')
    op.drop_index(op.f('ix_workoutsession_user_id'), table_name='workoutsession')
    op.drop_table('workoutsession')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_exercise_id'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
