"""add tags column to wardrobe_item

Revision ID: 58b0c0942f00
Revises: ac5606124f3f
Create Date: 2026-06-22 17:12:33.075922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58b0c0942f00'
down_revision: Union[str, Sequence[str], None] = 'ac5606124f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wardrobe_item', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wardrobe_item', 'tags')
    # ### end Alembic commands ###
