"""Add serving columns to ComplexDish

Revision ID: 7f1a871b3961
Revises: 2dd722911712
Create Date: 2026-06-20 21:05:23.113141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f1a871b3961'
down_revision: Union[str, Sequence[str], None] = '2dd722911712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexdish', sa.Column('serving_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('complexdish', sa.Column('serving_qty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complexdish', 'serving_qty')
    op.drop_column('complexdish', 'serving_unit')
    # ### end Alembic commands ###
