"""add wardrobe_item table

Revision ID: ac5606124f3f
Revises: 7f1a871b3961
Create Date: 2026-06-22 16:27:37.627159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac5606124f3f'
down_revision: Union[str, Sequence[str], None] = '7f1a871b3961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobe_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=False),
    sa.Column('last_worn', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_item_user_id'), 'wardrobe_item', ['user_id'], unique=False)
    op.drop_column('workoutset', 'calories_burned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutset', sa.Column('calories_burned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_wardrobe_item_user_id'), table_name='wardrobe_item')
    op.drop_table('wardrobe_item')
    # ### end Alembic commands ###
