"""add notes column to foodlog table

Revision ID: ce88a35c104e
Revises: 77b04eee3612
Create Date: 2026-06-16 17:16:33.264316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce88a35c104e'
down_revision: Union[str, Sequence[str], None] = '77b04eee3612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodlog', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodlog', 'notes')
    # ### end Alembic commands ###
